### ISSUE TITLE
CDSify in C# for .NET Core

### ISSUE THREAD

**Issue by ralphwest1** [scottdurow/dataverse-ify#10]
Hi Scott, Thanks for the great library and your course on PCF!
Is there a package you would know of or recommend with the same functionality as your Typescript Datavers-ify, except in C# for .NET Core that would let you generate early bound classes and work with the WebAPI similar to working with the .NET Framework Org Service?

**Comment by scottdurow** [comment]
Hi @ralphwest1 - glad you are finding it helpful!

Dataverse-ify essentially tries to give as close a behaviour as the C# sdk that can be used with early bound classes. The dotnetcore version is in alpha - https://github.com/microsoft/PowerPlatform-CdsServiceClient
