### ISSUE TITLE
Ability to output early bound classes only

### ISSUE THREAD

**Issue by filcole** [scottdurow/dataverse-ify#2]
Hi Scott,
Really interesting stuff thanks for sharing. I think the "early bound" generation of the entity classes that are compatible with @types/xrm is really nice. Would it be possible to add an option to solely generate those classes?  That might make CDSify easier to get integrated with existing code bases.

**Comment by scottdurow** [comment]
Thanks @filcole for the encouragement. The template and types cdsify uses are fully customisable (I’ll post an example shortly but you can use eject to create a project specific set of templates) - however the main point of cdsify is that it removes the need to use raw webapi/odata shapes that have lots of additional un-obvious fields and oddities! 😉

If you want a low barrier to entry route - this might be of interest- https://github.com/scottdurow/cdsify/wiki/Using-cdsify-without-CdsServiceClient
