### ISSUE TITLE
Question: Form Enum?

### ISSUE THREAD

**Issue by DSTAlan** [scottdurow/dataverse-ify#29]
Is it possible to generate an enum to allow entity forms to be referenced?  So, for example, if I want to use Xrm.Navigation.openForm I could use something like formId: Account.Forms.MyMainForm in entityFormOptions?

**Comment by scottdurow** [comment]
Hi @DSTAlan - thanks for the suggestion - dataverse-ify is primarily for calling the WebApi - so I think this suggestion would be better suited in https://github.com/delegateas/XrmDefinitelyTyped.

I'll close this for now - but if you feel really strongly, please feel free to re-open!

**Comment by alanrroberts** [comment]
OK thanks @scottdurow
