### ISSUE TITLE
Compatible with On-Premise 8.2

### ISSUE THREAD

**Issue by kschepperly** [scottdurow/dataverse-ify#8]
Hi Scott,
Is it possible to use dataverse-ify, specifically dataverse-gen, with Dynamics 365 v8.2 On-Premise using AD authentication?

**Comment by scottdurow** [comment]
Hi @kschepperly - dataverse-gen and dataverse-ify only work with Power Apps online.
I have no plans to implement back support for V8.2 On-Premise.
